<?php

namespace Modules\Earning\database\seeders;

use Illuminate\Database\Seeder;

class CommissionEarningsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('commission_earnings')->delete();
        if (env('IS_DUMMY_DATA')){
        \DB::table('commission_earnings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'employee_id' => 18,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 1,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'unpaid',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:53:24',
                'updated_at' => '2024-05-27 05:57:18',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 1,
                'commission_amount' => 90.0,
                'user_type' => 'admin',
                'commission_status' => 'unpaid',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:53:24',
                'updated_at' => '2024-05-27 05:57:18',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'employee_id' => 20,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 2,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'pending',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:53:50',
                'updated_at' => '2024-05-27 05:53:50',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 2,
                'commission_amount' => 90.0,
                'user_type' => 'admin',
                'commission_status' => 'pending',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:53:50',
                'updated_at' => '2024-05-27 05:53:50',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'employee_id' => 19,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 3,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'pending',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:54:19',
                'updated_at' => '2024-05-27 05:54:19',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 3,
                'commission_amount' => 90.0,
                'user_type' => 'admin',
                'commission_status' => 'pending',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:54:19',
                'updated_at' => '2024-05-27 05:54:19',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'employee_id' => 18,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 4,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'pending',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:54:46',
                'updated_at' => '2024-05-27 05:54:46',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 4,
                'commission_amount' => 90.0,
                'user_type' => 'admin',
                'commission_status' => 'pending',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:54:46',
                'updated_at' => '2024-05-27 05:54:46',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'employee_id' => 20,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 5,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'pending',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:55:18',
                'updated_at' => '2024-05-27 05:55:18',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 5,
                'commission_amount' => 90.0,
                'user_type' => 'admin',
                'commission_status' => 'pending',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:55:18',
                'updated_at' => '2024-05-27 05:55:18',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'employee_id' => 18,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 6,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'unpaid',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:56:25',
                'updated_at' => '2024-05-27 05:57:38',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 6,
                'commission_amount' => 90.0,
                'user_type' => 'admin',
                'commission_status' => 'unpaid',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:56:25',
                'updated_at' => '2024-05-27 05:57:38',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'employee_id' => 21,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 7,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'unpaid',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:35:09',
                'updated_at' => '2024-05-27 06:39:17',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 7,
                'commission_amount' => 3.0,
                'user_type' => 'admin',
                'commission_status' => 'unpaid',
                'commissions' => '[{"id":1,"title":"Admin Fees","commission_type":"fixed","commission_value":3,"type":"admin_fees","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:35:09',
                'updated_at' => '2024-05-27 06:39:17',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'employee_id' => 3,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 7,
                'commission_amount' => 87.0,
                'user_type' => 'vendor',
                'commission_status' => 'unpaid',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:35:09',
                'updated_at' => '2024-05-27 06:39:17',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'employee_id' => 22,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 8,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'pending',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:35:47',
                'updated_at' => '2024-05-27 06:35:47',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 8,
                'commission_amount' => 3.0,
                'user_type' => 'admin',
                'commission_status' => 'pending',
                'commissions' => '[{"id":1,"title":"Admin Fees","commission_type":"fixed","commission_value":3,"type":"admin_fees","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:35:47',
                'updated_at' => '2024-05-27 06:35:47',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'employee_id' => 4,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 8,
                'commission_amount' => 87.0,
                'user_type' => 'vendor',
                'commission_status' => 'pending',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:35:47',
                'updated_at' => '2024-05-27 06:35:47',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'employee_id' => 18,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 9,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'pending',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:36:19',
                'updated_at' => '2024-05-27 06:36:19',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 9,
                'commission_amount' => 90.0,
                'user_type' => 'admin',
                'commission_status' => 'pending',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:36:19',
                'updated_at' => '2024-05-27 06:36:19',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'employee_id' => 22,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 10,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'pending',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:36:49',
                'updated_at' => '2024-05-27 06:36:49',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 10,
                'commission_amount' => 3.0,
                'user_type' => 'admin',
                'commission_status' => 'pending',
                'commissions' => '[{"id":1,"title":"Admin Fees","commission_type":"fixed","commission_value":3,"type":"admin_fees","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:36:49',
                'updated_at' => '2024-05-27 06:36:49',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'employee_id' => 4,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 10,
                'commission_amount' => 87.0,
                'user_type' => 'vendor',
                'commission_status' => 'pending',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:36:49',
                'updated_at' => '2024-05-27 06:36:49',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'employee_id' => 21,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 11,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'pending',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:37:31',
                'updated_at' => '2024-05-27 06:37:31',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 11,
                'commission_amount' => 3.0,
                'user_type' => 'admin',
                'commission_status' => 'pending',
                'commissions' => '[{"id":1,"title":"Admin Fees","commission_type":"fixed","commission_value":3,"type":"admin_fees","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:37:31',
                'updated_at' => '2024-05-27 06:37:31',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'employee_id' => 3,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 11,
                'commission_amount' => 87.0,
                'user_type' => 'vendor',
                'commission_status' => 'pending',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:37:31',
                'updated_at' => '2024-05-27 06:37:31',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'employee_id' => 20,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 12,
                'commission_amount' => 60.0,
                'user_type' => 'doctor',
                'commission_status' => 'unpaid',
                'commissions' => '[{"id":3,"title":"Doctor Commission","commission_type":"percentage","commission_value":2,"type":"doctor_commission","status":1,"created_by":null,"updated_by":null,"deleted_by":null,"created_at":"2024-05-27T05:50:18.000000Z","updated_at":"2024-05-27T05:50:18.000000Z","deleted_at":null}]',
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:38:20',
                'updated_at' => '2024-05-27 06:39:06',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'employee_id' => 1,
                'commissionable_type' => 'Modules\\Appointment\\Models\\Appointment',
                'commissionable_id' => 12,
                'commission_amount' => 90.0,
                'user_type' => 'admin',
                'commission_status' => 'unpaid',
                'commissions' => NULL,
                'payment_date' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:38:20',
                'updated_at' => '2024-05-27 06:39:06',
                'deleted_at' => NULL,
            ),
        ));
        }
    }
}
