<?php

namespace Modules\Product\database\seeders;

use Illuminate\Database\Seeder;

class ProductCategoryMappingsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('product_category_mappings')->delete();

        \DB::table('product_category_mappings')->insert([
            0 => [
                'id' => 1,
                'product_id' => 1,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'product_id' => 2,
                'category_id' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'product_id' => 3,
                'category_id' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'product_id' => 4,
                'category_id' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            4 => [
                'id' => 5,
                'product_id' => 5,
                'category_id' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            5 => [
                'id' => 6,
                'product_id' => 6,
                'category_id' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            6 => [
                'id' => 7,
                'product_id' => 7,
                'category_id' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            7 => [
                'id' => 8,
                'product_id' => 8,
                'category_id' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            8 => [
                'id' => 9,
                'product_id' => 9,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            9 => [
                'id' => 10,
                'product_id' => 10,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            10 => [
                'id' => 11,
                'product_id' => 11,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            11 => [
                'id' => 12,
                'product_id' => 12,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            12 => [
                'id' => 13,
                'product_id' => 13,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            13 => [
                'id' => 14,
                'product_id' => 14,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            14 => [
                'id' => 15,
                'product_id' => 15,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            15 => [
                'id' => 16,
                'product_id' => 16,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            16 => [
                'id' => 17,
                'product_id' => 17,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            17 => [
                'id' => 18,
                'product_id' => 18,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            18 => [
                'id' => 19,
                'product_id' => 19,
                'category_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            19 => [
                'id' => 20,
                'product_id' => 20,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            20 => [
                'id' => 21,
                'product_id' => 21,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            21 => [
                'id' => 22,
                'product_id' => 22,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            22 => [
                'id' => 23,
                'product_id' => 23,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            23 => [
                'id' => 24,
                'product_id' => 24,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            24 => [
                'id' => 25,
                'product_id' => 25,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            25 => [
                'id' => 26,
                'product_id' => 26,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            26 => [
                'id' => 27,
                'product_id' => 27,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            27 => [
                'id' => 28,
                'product_id' => 28,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            28 => [
                'id' => 29,
                'product_id' => 29,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            29 => [
                'id' => 30,
                'product_id' => 30,
                'category_id' => 3,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            30 => [
                'id' => 31,
                'product_id' => 31,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            31 => [
                'id' => 32,
                'product_id' => 32,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            32 => [
                'id' => 33,
                'product_id' => 33,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            33 => [
                'id' => 34,
                'product_id' => 34,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            34 => [
                'id' => 35,
                'product_id' => 35,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            35 => [
                'id' => 36,
                'product_id' => 36,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            36 => [
                'id' => 37,
                'product_id' => 37,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            37 => [
                'id' => 38,
                'product_id' => 38,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            38 => [
                'id' => 39,
                'product_id' => 39,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            39 => [
                'id' => 40,
                'product_id' => 40,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            40 => [
                'id' => 41,
                'product_id' => 41,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            41 => [
                'id' => 42,
                'product_id' => 42,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            42 => [
                'id' => 43,
                'product_id' => 43,
                'category_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            43 => [
                'id' => 44,
                'product_id' => 44,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            44 => [
                'id' => 45,
                'product_id' => 45,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            45 => [
                'id' => 46,
                'product_id' => 46,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            46 => [
                'id' => 47,
                'product_id' => 47,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            47 => [
                'id' => 48,
                'product_id' => 48,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            48 => [
                'id' => 49,
                'product_id' => 49,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            49 => [
                'id' => 50,
                'product_id' => 50,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            50 => [
                'id' => 51,
                'product_id' => 51,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            51 => [
                'id' => 52,
                'product_id' => 52,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            52 => [
                'id' => 53,
                'product_id' => 53,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            53 => [
                'id' => 54,
                'product_id' => 54,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            54 => [
                'id' => 55,
                'product_id' => 55,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            55 => [
                'id' => 56,
                'product_id' => 56,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            56 => [
                'id' => 57,
                'product_id' => 57,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            57 => [
                'id' => 58,
                'product_id' => 58,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            58 => [
                'id' => 59,
                'product_id' => 59,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            59 => [
                'id' => 60,
                'product_id' => 60,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            60 => [
                'id' => 61,
                'product_id' => 61,
                'category_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            61 => [
                'id' => 62,
                'product_id' => 62,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            62 => [
                'id' => 63,
                'product_id' => 63,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            63 => [
                'id' => 64,
                'product_id' => 64,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            64 => [
                'id' => 65,
                'product_id' => 65,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            65 => [
                'id' => 66,
                'product_id' => 66,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            66 => [
                'id' => 67,
                'product_id' => 67,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            67 => [
                'id' => 68,
                'product_id' => 68,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            68 => [
                'id' => 69,
                'product_id' => 69,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            69 => [
                'id' => 70,
                'product_id' => 70,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            70 => [
                'id' => 71,
                'product_id' => 71,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            71 => [
                'id' => 72,
                'product_id' => 72,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            72 => [
                'id' => 73,
                'product_id' => 73,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            73 => [
                'id' => 74,
                'product_id' => 74,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            74 => [
                'id' => 75,
                'product_id' => 75,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            75 => [
                'id' => 76,
                'product_id' => 76,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            76 => [
                'id' => 77,
                'product_id' => 77,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            77 => [
                'id' => 78,
                'product_id' => 78,
                'category_id' => 6,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            78 => [
                'id' => 79,
                'product_id' => 79,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            79 => [
                'id' => 80,
                'product_id' => 80,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            80 => [
                'id' => 81,
                'product_id' => 81,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            81 => [
                'id' => 82,
                'product_id' => 82,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            82 => [
                'id' => 83,
                'product_id' => 83,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            83 => [
                'id' => 84,
                'product_id' => 84,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            84 => [
                'id' => 85,
                'product_id' => 85,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            85 => [
                'id' => 86,
                'product_id' => 86,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            86 => [
                'id' => 87,
                'product_id' => 87,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            87 => [
                'id' => 88,
                'product_id' => 88,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            88 => [
                'id' => 89,
                'product_id' => 89,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            89 => [
                'id' => 90,
                'product_id' => 90,
                'category_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            90 => [
                'id' => 91,
                'product_id' => 91,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            91 => [
                'id' => 92,
                'product_id' => 92,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            92 => [
                'id' => 93,
                'product_id' => 93,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            93 => [
                'id' => 94,
                'product_id' => 94,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            94 => [
                'id' => 95,
                'product_id' => 95,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            95 => [
                'id' => 96,
                'product_id' => 96,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            96 => [
                'id' => 97,
                'product_id' => 97,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            97 => [
                'id' => 98,
                'product_id' => 98,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            98 => [
                'id' => 99,
                'product_id' => 99,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            99 => [
                'id' => 100,
                'product_id' => 100,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            100 => [
                'id' => 101,
                'product_id' => 101,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            101 => [
                'id' => 102,
                'product_id' => 102,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            102 => [
                'id' => 103,
                'product_id' => 103,
                'category_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            103 => [
                'id' => 104,
                'product_id' => 104,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            104 => [
                'id' => 105,
                'product_id' => 105,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            105 => [
                'id' => 106,
                'product_id' => 106,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            106 => [
                'id' => 107,
                'product_id' => 107,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            107 => [
                'id' => 108,
                'product_id' => 108,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            108 => [
                'id' => 109,
                'product_id' => 109,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            109 => [
                'id' => 110,
                'product_id' => 110,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            110 => [
                'id' => 111,
                'product_id' => 111,
                'category_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
