<?php

namespace Modules\Clinic\database\seeders;

use Illuminate\Database\Seeder;
use Modules\Clinic\Models\ClinicsService;
use Modules\Clinic\Models\ClinicsCategory;
use Modules\Clinic\Models\Clinics;
use Modules\Clinic\Models\ClinicServiceMapping;

use Illuminate\Support\Arr;

class ClinicServiceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        if (env('IS_DUMMY_DATA')) {
            $data = [
                [
                    'slug' =>'cardiac-consultation',
                    'name' =>'Cardiac Consultation',
                    'category' =>'cardiology',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Expert consultation for heart health concerns. 💔',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/cardiac_consultation.png'),
                ],
                [
                    'slug' =>'echocardiography',
                    'name' =>'Echocardiography',
                    'category' =>'cardiology',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Non-invasive imaging to assess heart function. 🩺',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>60,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/echocardiography.png'),
                ],
                [
                    'slug' =>'angioplasty',
                    'name' =>'Angioplasty',
                    'category' =>'cardiology',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Procedure to widen narrowed or blocked blood vessels. 🩸',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/angioplasty.png'),
                ],
                [
                    'slug' =>'electrophysiology-study-eps',
                    'name' =>'Electrophysiology Study (EPS)',
                    'category' =>'electrophysiology',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Diagnostic procedure to evaluate heart rhythm abnormalities. ⚡',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/electrophysiology_study.png'),
                ],
                [
                    'slug' =>'cardiac-ablation',
                    'name' =>'Cardiac Ablation',
                    'category' =>'electrophysiology',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Treatment to correct heart rhythm problems by destroying abnormal heart tissue. 🔥',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/cardiac_ablation.png'),
                ],

                [
                    'slug' =>'implantable-cardioverter-defibrillator-icd-placement',
                    'name' =>'Implantable Cardioverter Defibrillator (ICD) Placement',
                    'category' =>'electrophysiology',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgical procedure to implant a device that corrects dangerous heart rhythms. 💓',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/implantable_cardioverter_defibrillator_placement.png'),
                ],
                [
                    'slug' =>'holter-monitoring',
                    'name' =>'Holter Monitoring',
                    'category' =>'heart-monitoring',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Continuous heart rhythm monitoring over a period of time using a portable device. 📈',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/holter_monitoring.png'),
                ],
                [
                    'slug' =>'event-monitoring',
                    'name' =>'Event Monitoring',
                    'category' =>'heart-monitoring',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Recording of heart activity during specific events or symptoms using a portable device. 📊',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/event_monitoring.png'),
                ],
                [
                    'slug' =>'implantable-loop-recorder-ilr',
                    'name' =>'Implantable Loop Recorder (ILR)',
                    'category' =>'heart-monitoring',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Long-term monitoring of heart rhythm with a small device implanted under the skin. ⏰',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/implantable_loop_recorder.png'),
                ],
                [
                    'slug' =>'hypertension-screening',
                    'name' =>'Hypertension Screening',
                    'category' =>'heart-monitoring',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Evaluation of blood pressure to detect and assess hypertension. 🩺',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/hypertension_management.png'),
                ],

                [
                    'slug' =>'diagnostic-coronary-angiography',
                    'name' =>'Diagnostic Coronary Angiography',
                    'category' =>'coronary-angiography',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Procedure to visualize and assess coronary artery blockages. 🩺',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/diagnostic_coronary_angiography.png'),
                ],
                [
                    'slug' =>'percutaneous-coronary-intervention-pci',
                    'name' =>'Percutaneous Coronary Intervention (PCI)',
                    'category' =>'coronary-angiography',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Minimally invasive procedure to open blocked coronary arteries. ⚡',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/percutaneous_coronary_intervention.png'),
                ],
                [
                    'slug' =>'coronary-artery-bypass-grafting-cabg',
                    'name' =>'Coronary Artery Bypass Grafting (CABG)',
                    'category' =>'coronary-angiography',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgical procedure to bypass blocked coronary arteries. ✂️',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/coronary_artery_bypass_grafting.png'),
                ],
                [
                    'slug' =>'genetic-testing-for-cardiac-conditions',
                    'name' =>'Genetic Testing for Cardiac Conditions',
                    'category' =>'genetic-cardiology-services',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Screening for genetic factors contributing to heart diseases. 🧬',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/genetic_testing_for_cardiac_conditions.png'),
                ],
                [
                    'slug' =>'genetic-counseling-for-heart-diseases',
                    'name' =>'Genetic Counseling for Heart Diseases',
                    'category' =>'genetic-cardiology-services',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Counseling to understand and manage genetic risks of heart disorders. 💬',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/genetic_counseling_for_heart_diseases.png'),
                ],
                [
                    'slug' =>'family-screening-for-inherited-heart-disorders',
                    'name' =>'Family Screening for Inherited Heart Disorders',
                    'category' =>'genetic-cardiology-services',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Screening family members for inherited heart conditions. 👨‍👩‍👧‍👦',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/family_screening_for_inherited_heart_disorders.png'),
                ],
                [
                    'slug' =>'orthopedic-sergery',
                    'name' =>'Orthopedic Sergery',
                    'category' =>'orthotics-and-prosthetics',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Comprehensive surgical procedures for musculoskeletal conditions. 🏥',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/orthopedic_sergery.png'),
                ],
                [
                    'slug' =>'prosthetic-limb-fitting',
                    'name' =>'Prosthetic Limb Fitting',
                    'category' =>'orthotics-and-prosthetics',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Fitting and adjustment of prosthetic limbs for mobility and function. 🦿',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/prosthetic_limb_fitting.png'),
                ],
            
                [
                    'slug' =>'hip-replacement',
                    'name' =>'hip-replacement',
                    'category' =>'joint-replacement',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgical procedure to replace a damaged hip joint with an artificial one. 🦵',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/hip_replacement.png'),
                ],
                [
                    'slug' =>'knee-replacement',
                    'name' =>'Knee Replacement',
                    'category' =>'joint-replacement',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgery to replace a damaged knee joint with a prosthetic implant. 🦵',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/knee_replacement.png'),
                ],
                [
                    'slug' =>'shoulder-replacement',
                    'name' =>'Shoulder Replacement',
                    'category' =>'joint-replacement',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgical procedure to replace a damaged shoulder joint with an artificial one. 🦋',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/shoulder_replacement.png'),
                ],
                [
                    'slug' =>'spinal-fusion-surgery',
                    'name' =>'Spinal Fusion Surgery',
                    'category' =>'spine-care',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgical technique to join two or more vertebrae in the spine. ⛓️',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/spinal_fusion_surgery.png'),
                ],
                [
                    'slug' =>'discectomy',
                    'name' =>'Discectomy',
                    'category' =>'spine-care',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgical removal of herniated disc material pressing on a nerve root or the spinal cord. 🔪',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/discectomy.png'),
                ],
                [
                    'slug' =>'spinal-decompression-treatment',
                    'name' =>'Spinal Decompression Treatment',
                    'category' =>'spine-care',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Non-surgical treatment to relieve pressure on spinal discs and nerves. 🌀',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/spinal_decompression_treatment.png'),
                ],
                [
                    'slug' =>'bone-density-testing',
                    'name' =>'Bone Density Testing',
                    'category' =>'osteoporosis',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Diagnostic test to measure bone density and assess the risk of fractures. 💀',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/bone_density_testing.png'),
                ],
                [
                    'slug' =>'osteoporosis-medication-treatment',
                    'name' =>'Osteoporosis Medication Treatment',
                    'category' =>'osteoporosis',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Treatment plan to manage osteoporosis and prevent bone loss. 💊',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/osteoporosis_medication_treatment.png'),
                ],
                [
                    'slug' =>'laparoscopic-surgery',
                    'name' =>'Laparoscopic Surgery',
                    'category' =>'minimally-invasive-surgery',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Minimally invasive surgical technique using small incisions and a camera. 🩹',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/laparoscopic_surgery.png'),
                ],
                [
                    'slug' =>'endoscopic-surgery',
                    'name' =>'Endoscopic Surgery',
                    'category' =>'minimally-invasive-surgery',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgical procedure performed through a small incision with an endoscope. 🩹',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/endoscopic_surgery.png'),
                ],
                [
                    'slug' =>'robotic-surgery',
                    'name' =>'Robotic Surgery',
                    'category' =>'minimally-invasive-surgery',
                    'clinic'=> 'heartcare-orthocare-center',
                    'description' =>'Surgical technique performed with the assistance of robotic arms controlled by a surgeon. 🤖',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/robotic_surgery.png'),
                ],
                [
                    'slug' =>'routine-check-ups-and-physical-examinations',
                    'name' =>'Routine Check-ups and Physical Examinations',
                    'category' =>'primary-care',
                    'clinic'=> 'harmony-medical-center',
                    'description' =>'Regular health check-ups to monitor your well-being. 👩‍⚕️ ',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/routine_check_ups_and_physical_examinations.png'),
                ],
                [
                    'slug' =>'diagnosis-and-treatment-of-common-illnesses',
                    'name' =>'Diagnosis and Treatment of Common Illnesses',
                    'category' =>'primary-care',
                    'clinic'=> 'harmony-medical-center',
                    'description' =>'Expert care for everyday health issues like colds and flu. 💊 ',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/diagnosis_and_treatment_of_common_illnesses.png'),
                ],
                [
                    'slug' =>'vaccinations-and-immunizations',
                    'name' =>'Vaccinations and Immunizations',
                    'category' =>'primary-care',
                    'clinic'=> 'harmony-medical-center',
                    'description' =>'Protect yourself and your loved ones with timely vaccinations. 💉',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/vaccinations_and_immunizations.png'),
                ],
                [
                    'slug' =>'acupuncture',
                    'name' =>'Acupuncture',
                    'category' =>'integrative-health',
                    'clinic'=> 'harmony-medical-center',
                    'description' =>'Traditional healing through precise needle therapy.📍',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/acupuncture.png'),
                ],
                [
                    'slug' =>'nutritional-supplements-and-dietary-counseling',
                    'name' =>'Nutritional Supplements and Dietary Counseling',
                    'category' =>'integrative-health',
                    'clinic'=> 'harmony-medical-center',
                    'description' =>'Personalized guidance for optimal nutrition. 🥦',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/nutritional_supplements_and_dietary_counseling.png'),
                ],
                [
                    'slug' =>'pediatric-primary-care',
                    'name' =>'Pediatric Primary Care',
                    'category' =>'pediatrics',
                    'clinic'=> 'harmony-medical-center',
                    'description' =>'Comprehensive medical care tailored to meet your childs needs. 👨‍⚕️👧',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/pediatric_primary_care.png'),
                ],
                [
                    'slug' =>'childhood-illness-management',
                    'name' =>'Childhood Illness Management',
                    'category' =>'pediatrics',
                    'clinic'=> 'harmony-medical-center',
                    'description' =>'Expert care for common childhood illnesses and conditions. 🤒💊',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/childhood_illness_management.png'),
                ],




                [
                    'slug' =>'teeth-cleaning',
                    'name' =>'Teeth Cleaning',
                    'category' =>'general-dentistry',
                    'clinic'=> 'wellness-dental-clinic',
                    'description' =>'Professional cleaning to remove plaque and tartar for a healthy smile. 😁✨',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/teeth_cleaning.png'),
                ],
                [
                    'slug' =>'fillings',
                    'name' =>'Fillings',
                    'category' =>'general-dentistry',
                    'clinic'=> 'wellness-dental-clinic',
                    'description' =>'Restoring cavities and preserving teeth with durable dental fillings. 🦷💎',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/fillings.png'),
                ],
                [
                    'slug' =>'wisdom-teeth-removal',
                    'name' =>'Wisdom Teeth Removal',
                    'category' =>'oral-surgery',
                    'clinic'=> 'wellness-dental-clinic',
                    'description' =>'Surgically extracting problematic wisdom teeth to improve oral health. 💡🦷',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/wisdom_teeth_removal.png'),
                ],
                [
                    'slug' =>'dental-implant-surgery',
                    'name' =>'Dental Implant Surgery',
                    'category' =>'oral-surgery',
                    'clinic'=> 'wellness-dental-clinic',
                    'description' =>'Restoring missing teeth with permanent dental implants for a natural-looking smile. 💪🦷',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/dental_implant_surgery.png'),
                ],
                [
                    'slug' =>'tooth-extraction',
                    'name' =>'Tooth Extraction',
                    'category' =>'oral-surgery',
                    'clinic'=> 'wellness-dental-clinic',
                    'description' =>'Removing damaged or decayed teeth to alleviate pain and prevent further complications. 🪓🦷',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/tooth_extraction.png'),
                ],
                [
                    'slug' =>'dermal-fillers',
                    'name' =>'Dermal Fillers',
                    'category' =>'cosmetic-dermatology',
                    'clinic'=> 'dermatology-associates',
                    'description' =>'Enhancing facial volume and reducing wrinkles for a youthful appearance. 💉✨',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/dermal_fillers.png'),
                ],
                [
                    'slug' =>'chemical-peels',
                    'name' =>'Chemical Peels',
                    'category' =>'cosmetic-dermatology',
                    'clinic'=> 'dermatology-associates',
                    'description' =>'Renew and rejuvenate skin. 🔬',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/chemical_peels.png'),
                ],
                [
                    'slug' =>'skin-cance-removal',
                    'name' =>'Skin Cancer Removal',
                    'category' =>'mohs-surgery',
                    'clinic'=> 'dermatology-associates',
                    'description' =>'Surgical removal of cancerous skin lesions to promote healing and prevent spread. 🩹🌞',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/skin_cancer_removal.png'),
                ],
                [
                    'slug' =>'mohs-micrographic-surgery',
                    'name' =>'Mohs Micrographic Surgery',
                    'category' =>'mohs-surgery',
                    'clinic'=> 'dermatology-associates',
                    'description' =>'Highly precise technique for removing skin cancer while preserving healthy tissue. 🎨🔍',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/mohs_micrographic_surgery.png'),
                ],
                [
                    'slug' =>'cataract-surgery',
                    'name' =>'Cataract Surgery',
                    'category' =>'ophthalmology',
                    'clinic'=> 'visionPlus-eye-clinic',
                    'description' =>'Surgical removal of cataracts to restore clear vision and improve quality of life. 👁️‍🗨️🔪',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/cataract_surgery.png'),
                ],


                [
                    'slug' =>'LASIK-eye-surgery',
                    'name' =>'LASIK Eye Surgery',
                    'category' =>'ophthalmology',
                    'clinic'=> 'visionPlus-eye-clinic',
                    'description' =>'Laser vision correction to improve vision and reduce dependence on glasses or contacts. 👁️‍🗨️💫',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/lasik_eye_surgery.png'),
                ],
                [
                    'slug' =>'comprehensive-eye-examinations',
                    'name' =>'Comprehensive Eye Examinations',
                    'category' =>'optometry',
                    'clinic'=> 'visionPlus-eye-clinic',
                    'description' =>'Thorough evaluations to assess vision and eye health. 👁️‍🗨️🔍',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/comprehensive_eye_examinations.png'),
                ],
                [
                    'slug' =>'contact-lens-fitting',
                    'name' =>'Contact Lens Fitting',
                    'category' =>'optometry',
                    'clinic'=> 'visionPlus-eye-clinic',
                    'description' =>'Customized fittings for comfortable and clear vision with contact lenses. 👁️‍🗨️👓',
                    'charges' =>100,
                    'vendor_id' =>1,
                    'duration_min' =>30,
                    'status' =>1,
                    'is_video_consultancy' =>0,
                    'file_url' => public_path('/dummy-images/clinic/service/contact_lens_fitting.png'),
                ]

            ];
            foreach ($data as $key => $val) {
                $featureImage = $val['file_url'] ?? null;
                $clinicCategory = ClinicsCategory::where('slug',$val['category'])->first();

                $clinicService = Arr::except($val, [ 'file_url','category','clinic']);

                $clinicService['category_id'] = $clinicCategory->id;
                $clinicServiceData = ClinicsService::create($clinicService);
                if (isset($featureImage)) {
                    $this->attachFeatureImage($clinicServiceData, $featureImage);
                }
                if(!empty($val['clinic'])){
                    $service_mapping = explode(",",$val['clinic']);
                    foreach ($service_mapping as $key => $service) {
                            $clinic = Clinics::where('slug',$service)->first();
                            $mapping_data = [
                                'clinic_id' => $clinic->id,
                                'service_id' => $clinicServiceData->id
                            ];
                            ClinicServiceMapping::create($mapping_data);
                        # code...
                    }
                }

            }
        }
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
    private function attachFeatureImage($model, $publicPath)
    {
        if(!env('IS_DUMMY_DATA_IMAGE')) return false;

        $file = new \Illuminate\Http\File($publicPath);

        $media = $model->addMedia($file)->preservingOriginal()->toMediaCollection('file_url');

        return $media;

    }
}
