<?php


namespace Modules\Appointment\database\seeders;
use Illuminate\Database\Seeder;
use DateTime;


class AppointmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $currentDate = new DateTime();
        $onemonth = clone $currentDate;
        $onemonth->modify('1 month');

        $twomonth = clone $currentDate;
        $twomonth->modify('2 months');

        $beforeonemonth = clone $currentDate;
        $beforeonemonth->modify('-1 month');

        $beforetwomonth = clone $currentDate;
        $beforetwomonth->modify('-2 months');

        \DB::table('appointments')->delete();

        \DB::table('appointments')->insert(array (
            0 =>
            array (
                'id' => 1,
                'status' => 'checkout',
                'start_date_time' => $beforetwomonth->format('Y-m-d H:i:s'),
                'user_id' => 9,
                'clinic_id' => 1,
                'doctor_id' => 19,
                'appointment_date' => $beforetwomonth->format('Y-m-d'),
                'appointment_time' => $beforetwomonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 1,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:53:23',
                'updated_at' => '2024-05-27 05:57:18',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'status' => 'check_in',
                'start_date_time' => $beforeonemonth->format('Y-m-d H:i:s'),
                'user_id' => 10,
                'clinic_id' => 2,
                'doctor_id' => 20,
                'appointment_date' => $beforeonemonth->format('Y-m-d'),
                'appointment_time' =>  $beforeonemonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 30,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:53:49',
                'updated_at' => '2024-05-27 05:57:47',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'status' => 'confirmed',
                'start_date_time' => $currentDate->format('Y-m-d H:i:s'),
                'user_id' => 11,
                'clinic_id' => 3,
                'doctor_id' => 19,
                'appointment_date' => $currentDate->format('Y-m-d'),
                'appointment_time' => $currentDate->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 37,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:54:19',
                'updated_at' => '2024-05-27 05:54:19',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'status' => 'check_in',
                'start_date_time' =>$beforeonemonth->format('Y-m-d H:i:s'),
                'user_id' => 12,
                'clinic_id' => 1,
                'doctor_id' => 19,
                'appointment_date' => $beforeonemonth->format('Y-m-d'),
                'appointment_time' => $beforeonemonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 3,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:54:46',
                'updated_at' => '2024-05-27 05:54:46',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'status' => 'check_in',
                'start_date_time' => $beforeonemonth->format('Y-m-d H:i:s'),
                'user_id' => 13,
                'clinic_id' => 3,
                'doctor_id' => 20,
                'appointment_date' => $beforeonemonth->format('Y-m-d'),
                'appointment_time' => $beforeonemonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 39,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:55:18',
                'updated_at' => '2024-05-27 05:55:18',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'status' => 'checkout',
                'start_date_time' => $beforeonemonth->format('Y-m-d H:i:s'),
                'user_id' => 14,
                'clinic_id' => 2,
                'doctor_id' => 19,
                'appointment_date' => $beforeonemonth->format('Y-m-d'),
                'appointment_time' => $beforeonemonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 33,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 05:56:24',
                'updated_at' => '2024-05-27 05:57:38',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'status' => 'checkout',
                'start_date_time' => $beforeonemonth->format('Y-m-d H:i:s'),
                'user_id' => 15,
                'clinic_id' => 4,
                'doctor_id' => 21,
                'appointment_date' => $beforeonemonth->format('Y-m-d'),
                'appointment_time' => $beforeonemonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 42,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:35:08',
                'updated_at' => '2024-05-27 06:39:17',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'status' => 'check_in',
                'start_date_time' => $beforeonemonth->format('Y-m-d H:i:s'),
                'user_id' => 16,
                'clinic_id' => 5,
                'doctor_id' => 22,
                'appointment_date' => $beforeonemonth->format('Y-m-d'),
                'appointment_time' => $beforeonemonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 47,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:35:47',
                'updated_at' => '2024-05-27 06:38:38',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'status' => 'confirmed',
                'start_date_time' => $twomonth->format('Y-m-d H:i:s'),
                'user_id' => 9,
                'clinic_id' => 1,
                'doctor_id' => 19,
                'appointment_date' => $twomonth->format('Y-m-d'),
                'appointment_time' => $twomonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 1,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:36:19',
                'updated_at' => '2024-05-27 06:36:19',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'status' => 'confirmed',
                'start_date_time' => $twomonth->format('Y-m-d H:i:s'),
                'user_id' => 10,
                'clinic_id' => 5,
                'doctor_id' => 22,
                'appointment_date' => $twomonth->format('Y-m-d'),
                'appointment_time' => $twomonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 49,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:36:49',
                'updated_at' => '2024-05-27 06:36:49',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'status' => 'confirmed',
                'start_date_time' => $twomonth->format('Y-m-d H:i:s'),
                'user_id' => 11,
                'clinic_id' => 4,
                'doctor_id' => 21,
                'appointment_date' => $twomonth->format('Y-m-d'),
                'appointment_time' => $twomonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 44,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:37:31',
                'updated_at' => '2024-05-27 06:37:31',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'status' => 'checkout',
                'start_date_time' => $beforetwomonth->format('Y-m-d H:i:s'),
                'user_id' => 12,
                'clinic_id' => 3,
                'doctor_id' => 20,
                'appointment_date' => $beforetwomonth->format('Y-m-d'),
                'appointment_time' => $beforetwomonth->format('H:i:s'),
                'duration' => 30.0,
                'service_id' => 40,
                'appointment_extra_info' => NULL,
                'total_amount' => 150.0,
                'service_amount' => 100.0,
                'service_price' => 100.0,
                'meet_link' => NULL,
                'start_video_link' => NULL,
                'join_video_link' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2024-05-27 06:38:20',
                'updated_at' => '2024-05-27 06:39:06',
                'deleted_at' => NULL,
            ),
        ));


    }
}
